### ISSUE TITLE
Parameter query is not converted to correct type

### ISSUE THREAD

**Issue by davidnewcomb** [openapistack/openapi-backend#554]
I have a definition:
```
      parameters:
      - name: from
        in: query
        description: Which page to get
        required: false
        schema:
          type: integer
          format: int64
```
But when it hits my handler e.g.:
```
export async function newslist(c, req, res) {
    console.log('newslist:c.request.query: ' + JSON.stringify(c.request.query))
```
it becomes:
```
newslist:c.request.query: {"from":"123"}
```
instead of:
```
newslist:c.request.query: {"from":123}
```

So I have to do all the type converting which I would have thought openapi-backend would do for me.

On a similar note, I included the ajv-formats to use `date-time` string format and was expecting to get a native Javascript Date but I don't, I just get a string that's been parsed for correctness.

I think openapi-backend should do these kinds of conversions but if it can't, do you have an easy way for me to add type converters?
