### ISSUE TITLE
unknown format "date-time" ignored in schema

### ISSUE THREAD

**Issue by robogeek** [openapistack/openapi-backend#718]
The specification I'm working with uses ISO 8601 date-time strings, of course.  The declaration for the corresponding schema object is:

```yaml
    dateTime:
      type: string
      format: date-time
      description: datetime in ISO 8601 format
      example: 2023-06-15T09:30:00Z
```

When executing the test suite, a zillion error messages like this are printed:

```
unknown format "date-time" ignored in schema at path "#/properties/createdDateTime"
```

The messages go away when commenting the `format: date-time` specification.
