### ISSUE TITLE
unknown format "uri" ignored in schema

### ISSUE THREAD

**Issue by robogeek** [openapistack/openapi-backend#719]
The specification I'm working with deals with URLs in several fields, which are marked with `format: uri`.  For example:

```yaml
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type.
            When dereferenced, it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: 'about:blank'
          example: 'https://zalando.github.io/problem/constraint-violation'
```

When executing the test suite, the following message is printed a zillion times or so:

```
unknown format "uri" ignored in schema at path "#/properties/type"
```

Commenting out the `format: uri` thing eliminates the message.
