### ISSUE TITLE
Lack of Support for Form Explode Serialization in Query Parameters

### ISSUE THREAD

**Issue by acerola1** [openapistack/openapi-backend#722]
In the [openapi specification](https://swagger.io/docs/specification/serialization/#query) the style: form, explode: true method is the default object serialization. When I define a schema with these, for example:
```
parameters:
  - in: query
    name: id
    schema:
      type: object
      properties:
        role:
          type: string
        firstName:
          type: string
      style: form
      explode: true
```
And I call the mock api with the correct serialization: `/users?role=admin&firstName=Alex.`

I encounter a validation error indicating a missing "id" property, suggesting the library expects the object as a single parameter rather than exploded into individual properties.

Expected Behavior: The library should validate requests with exploded form serialization correctly, recognizing individual properties as part of the specified object parameter.

Is there any solution or workaround for this?
